# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: DenisLabrecque.ca
  fr: DenisLabrecque.ca
email: your-email@domain.com
description:
  en: DenisLabrecque.ca is my portfolio. I have worked countless hours making musical compositions, drawings, short books and articles that I wish to share with you. This website is also a sounding board to the defense of the truth and the life, found in Jesus-Christ, the God of Heaven and the Saviour of our evil actions.
  fr: DenisLabrecque.ca est mon portfolio. J'ai travaillé des heures à des compositions musicales, des dessins, des livres courts et des articles que je désire partager avec vous. Ce site est aussi un centre d'affiche pour la défense de la vérité et de la vie, trouvée en Jésus-Christ, le dieu du ciel et le sauveur de nos mauvaises actions.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://denislabrecque.ca" # the base hostname & protocol for your site
twitter_username: denisglabrecque
github_username:  DenisLabrecque

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      author: "Denis G. Labrecque"
